### PR TITLE
Development Sprint #2

### PR DESCRIPTION
**Pull request by DavidOry**

### CODE REVIEW

**Comment by DavidOry** [comment]
@i-am-sijia 

Transit wiewer seems to be missing:
* ACE (Will add to data folder now)
* AC Transit (will add now)
* Capitol Corridor 
* CCTA
* Vine

**Comment by DavidOry** [comment]
@i-am-sijia 
The stop sequence for the VTA routes seems off. The others look good. Can you please have a look?

**Comment by i-am-sijia** [comment]
@DavidOry 

shapes.txt (`shape_id`) missing for:

- ACE
- CCTA
- Vine

`direction_id` is missing for Marguerite.

I was choosing representative trips by `route_id, tod, shape_id, direction_id`, that's why they are missing in the final result.  I will change my code if we can't find shapes for those.

**Comment by DavidOry** [comment]
Ah. That makes sense. I *believe* all the Marguerite routes are all loops.

**Comment by i-am-sijia** [comment]
Ok.  For the missing shapes ones, I will choose representative trips by 'route_id, tod, direction_id' and then we can still route them using OSMNX.

**Comment by DavidOry** [comment]
> Ok. For the missing shapes ones, I will choose representative trips by 'route_id, tod, direction_id' and then we can still route them using OSMNX.

That works for Vine and CCTA. ACE is a train, so you'll want to route to the train links added to the roadway network (or just draw straight lines between the stops).

**Comment by i-am-sijia** [comment]
@DavidOry I updated shortest path method, a lot of shapes now look much smoother and closer to the GTFS stop plot.

**Comment by DavidOry** [comment]
@gshivaraman 
Please update the Project Cards I originally created as well to include `model_link_id`, e.g., [this one](https://github.com/BayAreaMetro/travel-model-two-networks/blob/develop/project_cards/year_2015_attributes_exclude_trucks_i580.yml).

**Comment by DavidOry** [comment]
@gshivaraman 
All of the express lanes should have a USECLASS of 4, rather than 3 (if they are 3, then SOVs are excluded; if they are 4, then SOVs can use them for a price and the price for HOV3+ can be zero).

**Comment by DavidOry** [comment]
@i-am-sijia 
I re-factored the MTC Lasso module to keep it independent from Lasso and updated the 01 notebook [here](https://github.com/BayAreaMetro/travel-model-two-networks/blob/develop/notebooks/01-attribute-and-make-pickles.ipynb). I also moved the input standard network files to `processed/version_02`. Can you please have a look at my notebook and fix the transit bug?

**Comment by DavidOry** [comment]
@i-am-sijia: can you please add a `link.feather` to `processed/version_02/`?

**Comment by i-am-sijia** [comment]
@DavidOry done: 
1. add centroid connector when making travel model network
2. remove ft, assignable calculation from roadway_standard_to_mtc_network()
3. ML inherit ft and assignable from GP

**Pull request merged**
