### PR TITLE
Tidy up Task 12 Deliverables

### PR DESCRIPTION
**Pull request by DavidOry**

### CODE REVIEW

**Comment by DavidOry** [comment]
@i-am-sijia 
Can you please remove `FARESYSTEM` for routes with `FARESYSTEM=0`?

**Comment by DavidOry** [comment]
@i-am-sijia 
A few routes have 'operator=0', which is throwing an error. Can you please check these? If the table is missing some operators, please move to 99 for now and add to the table for us to add.

**Comment by i-am-sijia** [comment]
> A few routes have 'operator=0', which is throwing an error. Can you please check these? If the table is missing some operators, please move to 99 for now and add to the table for us to add.

Yes, the operator code is missing for Mountain View.  Sorry, I should have asked what value to use, but instead I assumed we could use 0.  Added comment in PRD.

**Comment by DavidOry** [comment]
@i-am-sijia 
`SHORTNAME` cannot include `-`. Can you replace the dashes with underscores `_`?

**Comment by DavidOry** [comment]
Two more problems, @i-am-sijia:
1. `SHORTNAME` cannot include spaces. Can you please replace with underscores?
2. `LONGNAME` cannot be longer than 30 characters. Can you please truncate?

**Comment by i-am-sijia** [comment]
> `SHORTNAME` cannot include spaces. Can you please replace with underscores?

@DavidOry "South SF - SF Ferry" becomes "South_SF___SF_Ferry", is it OK?  Or we can remove spaces instead.

**Comment by DavidOry** [comment]
@i-am-sijia: 
Last one (I hope): `LINE NAME` also needs to be 30 chars.

**Comment by DavidOry** [comment]
> > `SHORTNAME` cannot include spaces. Can you please replace with underscores?
> 
> @DavidOry "South SF - SF Ferry" becomes "South_SF___SF_Ferry", is it OK? Or we can remove spaces instead.

It would be better if we could have something where we can go back and forth. Perhaps "_" for dashes "." for spaces? Let's give that a try.

**Pull request merged**
